@extends('layouts.masterlayout')

@section('content')
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Create Quotation</h4>

    <form action="{{ route('quotations.store') }}" method="POST">
      @csrf

      <!-- Customer Info -->
      <div class="mb-3">
        <label>Customer Name</label>
        <input type="text" name="customer_name" class="form-control @error('customer_name') is-invalid @enderror" value="{{ old('customer_name') }}">
         @error('customer_name')
          <div class="invalid-feedback">{{ $message }}</div>
        @enderror
      </div>

      <div class="mb-3">
        <label>Mobile Number</label>
        <input type="text" name="mobile_number" class="form-control" required>
      </div>

      <div class="mb-3">
        <label>Generated By</label>
        <input type="text" name="generated_by" value="{{ auth()->user()->email }}" readonly class="form-control">
      </div>

      <div class="mb-3">
        <label>Generated For</label>
        <input type="text" name="to_name" class="form-control" required>

      </div>

      <!-- Dates -->
      <div class="row">
        <div class="col-md-6 mb-3">
          <label>Quotation Date</label>
          <input type="date" name="quotation_date" value="{{ date('Y-m-d') }}" class="form-control">
        </div>
        <div class="col-md-6 mb-3">
          <label>Valid Until</label>
          <input type="date" name="valid_until" class="form-control">
        </div>
      </div>

      <!-- Products -->
      <h5>Products</h5>
      <table class="table table-bordered" id="productsTable">
        <thead>
          <tr>
            <th>Product</th>
            <th width="120">Stock</th>
            <th width="120">Qty</th>
            <th width="140">Price</th>
          </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
          <tr>
            <td>
              <input type="checkbox"
                     class="product-checkbox"
                     data-stock="{{ $product->stock_quantity }}"
                     {{ $product->stock_quantity == 0 ? 'disabled' : '' }}
                     name="products[{{ $product->id }}][id]"
                     value="{{ $product->id }}">
              {{ $product->name }}

              @if($product->stock_quantity == 0)
                <span class="badge bg-danger ms-2">Out of stock</span>
              @endif
            </td>

            <td>
              <span class="badge bg-info">{{ $product->stock_quantity }}</span>
            </td>

            <td>
              <input type="number"
                     name="products[{{ $product->id }}][quantity]"
                     value="1"
                     min="1"
                     max="{{ $product->stock_quantity }}"
                     class="form-control quantity-input"
                     disabled>
            </td>

            <td>
              <input type="number"
                     name="products[{{ $product->id }}][unit_price]"
                     value="{{ $product->selling_price }}"
                     step="0.01"
                     class="form-control unit-price-input"
                     disabled>
            </td>
          </tr>
        @endforeach
        </tbody>
      </table>

      <!-- Tax / Discount -->
      <div class="row mt-3">
        <div class="col-md-4">
          <label>Tax %</label>
          <input type="number" step="0.01" name="tax_percent" value="0" class="form-control">
        </div>
        <div class="col-md-4">
          <label>Discount %</label>
          <input type="number" step="0.01" name="discount_percent" value="0" class="form-control">
        </div>
      </div>

      <button class="btn btn-success mt-4">Save Quotation</button>
      <a href="{{ route('quotations.index') }}" class="btn btn-light mt-4">Cancel</a>
    </form>
  </div>
</div>

<!-- ✅ 1️⃣ jQuery (only once, first) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- ✅ 2️⃣ Bootstrap JS (your template bundle) -->
<script src="{{ asset('assets/vendors/js/vendor.bundle.base.js') }}"></script>

<!-- ✅ 3️⃣ DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('.product-checkbox').forEach(cb => {
    const tr = cb.closest('tr');
    const qty = tr.querySelector('.quantity-input');
    const price = tr.querySelector('.unit-price-input');
    const stock = parseInt(cb.dataset.stock);

    cb.addEventListener('change', () => {
      if (stock === 0) {
        cb.checked = false;
        alert('This product is out of stock');
        return;
      }
      qty.disabled = !cb.checked;
      price.disabled = !cb.checked;
    });
  });
});
</script>
<script>
    $(document).ready(function () {
    if ($('#productsTable').length) {
        $('#productsTable').DataTable({
            pageLength: 10,
            order: [[0, 'asc']],
        });
    }
});
</script>
@endsection
