@extends('layouts.masterlayout')

@section('content')
<div class="col-12 grid-margin stretch-card">
<div class="card">
<div class="card-body">

<h4 class="card-title">Create Invoice</h4>

<form method="POST" action="{{ route('invoices.store') }}">
@csrf

{{-- Customer Name --}}
<div class="form-group">
    <label>Customer Name</label>
    <input type="text"
           name="customer_name"
           value="{{ old('customer_name') }}"
           class="form-control">
    @error('customer_name')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

{{-- Mobile --}}
<div class="form-group">
    <label>Mobile Number</label>
    <input type="text"
           name="mobile_number"
           value="{{ old('mobile_number') }}"
           class="form-control">
    @error('mobile_number')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

{{-- Generated By --}}
<div class="form-group">
    <label>Generated By</label>
    <input type="text"
           name="generated_by"
           value="{{ auth()->user()->email }}"
           class="form-control"
           readonly>
    @error('generated_by')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

{{-- Generated For --}}
<div class="form-group">
    <label>Generated For</label>
    <input type="text"
           name="to_name"
           value="{{ old('to_name') }}"
           class="form-control">
    @error('to_name')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

{{-- Invoice Date --}}
<div class="form-group">
    <label>Invoice Date</label>
    <input type="date"
           name="invoice_date"
           value="{{ old('invoice_date', date('Y-m-d')) }}"
           class="form-control">
    @error('invoice_date')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

{{-- Products --}}
<div class="form-group mt-4">
<label>Products</label>

<table class="table table-bordered" id="productsTable">
<thead>
<tr>
    <th>Select</th>
    <th>Product</th>
    <th>Stock</th>
    <th>Qty</th>
    <th>Price</th>
</tr>
</thead>
<tbody>

@foreach($products as $product)
<tr>
<td>
@if($product->stock_quantity > 0)
    <input type="checkbox"
           class="product-checkbox"
           name="products[{{ $product->id }}][selected]"
           value="1"
           {{ old("products.$product->id.selected") ? 'checked' : '' }}>
@else
    <span class="badge bg-danger">Out of Stock</span>
@endif

<input type="hidden"
       name="products[{{ $product->id }}][id]"
       value="{{ $product->id }}">
</td>

<td>{{ $product->name }}</td>

<td>
    <span class="badge bg-info">
        {{ $product->stock_quantity }}
    </span>
</td>

<td>
    <input type="number"
           name="products[{{ $product->id }}][quantity]"
           value="{{ old("products.$product->id.quantity", 1) }}"
           min="1"
           max="{{ $product->stock_quantity }}"
           class="form-control quantity-input"
           disabled>
    @error("products.$product->id.quantity")
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</td>

<td>
    <input type="number"
           name="products[{{ $product->id }}][unit_price]"
           value="{{ $product->selling_price }}"
           step="0.01"
           class="form-control unit-price-input"
           disabled>
</td>
</tr>
@endforeach

</tbody>
</table>

@error('products')
    <span class="text-danger small">{{ $message }}</span>
@enderror
</div>

{{-- Tax & Discount --}}
<div class="row mt-3">
<div class="col-md-4">
    <label>Tax</label>
    <input type="number"
           step="0.01"
           name="tax"
           id="tax_input"
           value="{{ old('tax', 0) }}"
           class="form-control">
    @error('tax')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>

<div class="col-md-4">
    <label>Discount</label>
    <input type="number"
           step="0.01"
           name="discount"
           id="discount_input"
           value="{{ old('discount', 0) }}"
           class="form-control">
    @error('discount')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>
</div>

{{-- Summary --}}
<div class="mt-4 bg-light p-3 rounded">
<p>Subtotal: ₹ <span id="subtotal">0.00</span></p>
<p>Tax: ₹ <span id="tax">0.00</span></p>
<p>Discount: ₹ <span id="discount">0.00</span></p>
<h5>Total: ₹ <span id="total">0.00</span></h5>

<div class="mt-3">
    <label><strong>Paid Amount</strong></label>
    <input type="number"
           step="0.01"
           name="paid_amount"
           value="{{ old('paid_amount', 0) }}"
           class="form-control">
    @error('paid_amount')
        <span class="text-danger small">{{ $message }}</span>
    @enderror
</div>
</div>

<button class="btn btn-primary mt-3">Save Invoice</button>
<a href="{{ route('invoices.index') }}" class="btn btn-light mt-3">Cancel</a>

</form>
</div>
</div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- ✅ 2️⃣ Bootstrap JS (your template bundle) -->
<script src="{{ asset('assets/vendors/js/vendor.bundle.base.js') }}"></script>

<!-- ✅ 3️⃣ DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>

<!-- ✅ 4️⃣ Your page-specific script -->
<script>
$(document).ready(function () {
    if ($('#productsTable').length) {
        $('#productsTable').DataTable({
            pageLength: 10,
            order: [[0, 'asc']],
        });
    }
});
</script>
{{-- JS --}}
<script>
document.addEventListener('DOMContentLoaded', function () {

const checkboxes = document.querySelectorAll('.product-checkbox');
const taxInput = document.getElementById('tax_input');
const discountInput = document.getElementById('discount_input');

function calculate() {
let subtotal = 0;

checkboxes.forEach(cb => {
if(cb.checked) {
let row = cb.closest('tr');
let qty = parseFloat(row.querySelector('.quantity-input').value) || 0;
let price = parseFloat(row.querySelector('.unit-price-input').value) || 0;
subtotal += qty * price;
}
});

let tax = parseFloat(taxInput.value) || 0;
let discount = parseFloat(discountInput.value) || 0;
let total = subtotal + tax - discount;

document.getElementById('subtotal').innerText = subtotal.toFixed(2);
document.getElementById('tax').innerText = tax.toFixed(2);
document.getElementById('discount').innerText = discount.toFixed(2);
document.getElementById('total').innerText = total.toFixed(2);
}

checkboxes.forEach(cb => {
let row = cb.closest('tr');
let qty = row.querySelector('.quantity-input');
let price = row.querySelector('.unit-price-input');

cb.addEventListener('change', () => {
qty.disabled = !cb.checked;
price.disabled = !cb.checked;
calculate();
});

qty.addEventListener('input', calculate);
price.addEventListener('input', calculate);
});

taxInput.addEventListener('input', calculate);
discountInput.addEventListener('input', calculate);
});
</script>
@endsection
